version: '3.8'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
#    ports:
#      - 80:8080
    depends_on:
      - db
    networks:
      - proxy
      - internal
    labels:
      - "traefik.http.routers.fireflyiii.entrypoints=web,websecure"
      - 'traefik.http.routers.fireflyiii.rule=Host(`${FRONTEND_RULE}`)'
      - "traefik.http.services.fireflyiii.loadbalancer.server.port=8080"
      - 'traefik.enable=true'
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - internal
    volumes:
      - firefly_iii_db:/var/lib/mysql
#  fidi:
#    image: fireflyiii/data-importer:latest
#    restart: always
#    env_file: .fidi.env
#    networks:
#      - proxy
#      - internal
#    labels:
#      - "traefik.http.routers.fireflyiiifidi.entrypoints=web,websecure"
#      - 'traefik.http.routers.fireflyiiifidi.rule=Host(`${FRONTEND_RULE_FIDI}`)'
#      - "traefik.http.services.fireflyiiifidi.loadbalancer.server.port=8080"
#      - 'traefik.enable=true'
##    ports:
##      - 8081:8080
#    depends_on:
#      - app
#  firefly-bot:
#    image: vjfalk1/firefly-telegram-bot:latest
#    environment:
#      - TELEGRAM_BOT_TOKEN=xxxxxx
#    volumes:
#      - ../telegram_bot/config:/config
#    networks:
#      - proxy
#      - internal
#    labels:
#      - "traefik.http.routers.fireflybot.entrypoints=web,websecure"
#      - 'traefik.http.routers.fireflybot.rule=Host(`${TRAEFIK_FRONTEND_RULE}`) && (PathPrefix(`/api`) || PathPrefix(`/telegram`))'
#      - "traefik.http.services.fireflybot.loadbalancer.server.port=8080"
#      - 'traefik.enable=true'

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  proxy:
    name: ${PROXY_NAME}
    external: true
  internal:
    driver: bridge
